#FROM registry.ng.bluemix.net/ibmnode
FROM node:latest

RUN mkdir /src

WORKDIR /src
COPY ./ /src

RUN npm install

EXPOSE 80
ENV VCAP_APP_PORT=80

ENV CUSTOMER_SERVICE=localhost:6379/customer

RUN wget -qO- https://github.com/amalgam8/amalgam8/releases/download/v1.0.0/a8sidecar.sh | sh
COPY config.yaml /opt/microservices/config.yaml

CMD [ "a8sidecar", "--config", "/opt/microservices/config.yaml" ]

